# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

energy_method <- function(sample_1, sample_2, num_bootstrap_reps, seed, type) {
    .Call(`_energymethod_energy_method`, sample_1, sample_2, num_bootstrap_reps, seed, type)
}

energy_method_complex <- function(sample_1, sample_2, num_bootstrap_reps, seed, type) {
    .Call(`_energymethod_energy_method_complex`, sample_1, sample_2, num_bootstrap_reps, seed, type)
}

